### ISSUE TITLE
Index checker plugin not working in Liferay DXP Platform 2023.Q4.4 

### ISSUE THREAD

**Issue by chiraggurav** [jorgediaz-lr/index-checker#19]
Hello @jorgediaz-lr, 
We are using your plugin and it works fine in version 7.3. Recently we migrated our application to **Liferay DXP Platform 2023.Q4.4** and the plugin does not work in this version. I tried to debug the code and noticed that method **ServiceUtil.getService** returns null for the **JournalArticle** model. 

Could you please provide some suggestions, so I will try to update the code and make it compatible with Liferay Quarterly release.

Thanks

**Comment by jorgediaz-lr** [comment]
Hi @chiraggurav 

I am on PTO for several months and I won't work until August and I cannot invest much personal time on this.

Nevertheless, I had a quick look at the code and it is true that it doesn't compile for newer versions of Liferay: I have changed in the gradle.properties file from GA75 to GA112 version  (_equivalent to 2024.Q1_) and there are several compilation errors due to missing java classes.

After applying some minor changes to the Index Checker code (see https://github.com/jorgediaz-lr/index-checker/compare/1.0.x...master) I was able to successfully compile it for GA112.

You can download an updated JAR file with the changes in this link: https://github.com/jorgediaz-lr/index-checker/actions/runs/9130427849/artifacts/1513682687

I wasn't able to test it in 2023.Q4 as I don't have any installation with that version, can you test it and tell me if it works?

**Comment by chiraggurav** [comment]
Hi @jorgediaz-lr,

Thanks for quick solution, sure I will verify your changes in 2023 Q4 version but shared link is not working for me. 
If possible can you share the correct download link so i will verify the changes

Below link is not working
https://github.com/jorgediaz-lr/index-checker/actions/runs/9130427849/artifacts/1513682687

**Comment by jorgediaz-lr** [comment]
Hi @chiraggurav 

It seems the generated files by the github actions are not public. 

Here it is the file, unzip it and deploy the JAR that it is inside: [index-checker.zip](https://github.com/jorgediaz-lr/index-checker/files/15375406/index-checker.zip)

**Comment by jorgediaz-lr** [comment]
Hi @chiraggurav

Did you have the chance to test the new version of index checker that I attached in my previous comment?

Thank you

**Comment by chiraggurav** [comment]
Hi @jorgediaz-lr  Thank you for quick help, I have verified the module in Liferay DXP Platform 2023.Q4.4 setup and its working perfectly fine as expected. 


Thanks :)

**Comment by jorgediaz-lr** [comment]
Officially published new Index Checker 1.1.0 for the new Liferay Quarterly Release versions, see https://github.com/jorgediaz-lr/index-checker#installation
